Add detail to project progression checklist
openjs-foundation/cross-project-council pull request #1085
Opened 2023-06-06 08:31 UTC by Relequestual

Resolves https://github.com/openjs-foundation/cross-project-council/issues/1026

Detail how people should indicate they are a projects representitives to join the CPC. Per https://github.com/openjs-foundation/cross-project-council/issues/1026#issuecomment-1577383503

2023-06-06 08:41 UTC, tobie requested changes
This is great. Blocking here to make sure we don't forget to update the checklist at https://github.com/openjs-foundation/project-status/blob/HEAD/.github/ISSUE_TEMPLATE/00-project-onboarding-checklist-template.md before we merge this.

2023-06-08 12:50 UTC, tobie commented on PROJECT_PROGRESSION.md
> +- [ ] Identify individuals from the project to join the CPC by opening an Issue in the CPC repository which identifies the individuals and the project
```suggestion
- [ ] Identify individuals from the project to join the CPC [by opening an issue in the CPC repository](https://github.com/openjs-foundation/cross-project-council/issues/new)
```

2023-08-24 14:36 UTC, Relequestual commented
> This is great. Blocking here to make sure we don't forget to update the checklist at https://github.com/openjs-foundation/project-status/blob/HEAD/.github/ISSUE_TEMPLATE/00-project-onboarding-checklist-template.md before we merge this.

PR now open: https://github.com/openjs-foundation/project-status/pull/69

2023-08-24 14:58 UTC, tobie approved these changes

2023-08-24 15:00 UTC, merged