Update GOVERNANCE.md
openjs-foundation/cross-project-council pull request #1134
Opened 2023-08-07 19:50 UTC by jasuarez90

Updated instructions for onboarding regular members. (Note: This is my first time doing a pull request)

2023-08-07 20:34 UTC, joesepi approved these changes

2023-08-07 20:34 UTC, joesepi commented
I wonder if this sort of process work should even be in the GOVERNANCE.md file.

2023-08-08 05:37 UTC, ljharb approved these changes
probably not, but it should be moved in a separate PR

2023-08-08 05:38 UTC, ljharb requested changes
`[OpenJS Foundation CPC directory][]` is now unused, is that intentional? If so, please remove the definition.

2023-08-08 05:38 UTC, ljharb commented on governance/GOVERNANCE.md
> +   * Operartions will add the member to the `cpc-private` email list
```suggestion
   * Operations will add the member to the `cpc-private` email list
```

2023-10-24 15:09 UTC, ljharb approved these changes

2023-10-24 16:50 UTC, mhdawson approved these changes
LGTM

2023-10-24 17:19 UTC, anonrig approved these changes

2023-10-24 19:01 UTC, merged