Update IP_POLICY_GUIDANCE.md
openjs-foundation/cross-project-council pull request #1245
Opened 2024-01-31 22:19 UTC by bensternthal

- Adds blue oak license to IP policy guidance
- Fixes reference to a PM that is no longer with LF

2024-01-31 22:26 UTC, mhdawson approved these changes
LGTM

2024-01-31 22:50 UTC, ljharb approved these changes

2024-01-31 23:17 UTC, tobie requested changes
Let's wait for the IP policy at https://ip-policy.openjsf.org to be updated. _(I'm also unsure if the decision is to allow projects to use that license or just dependencies of projects to do so.)_

To be clear, I'm just blocking so we don't end-up with a guidance document that's ahead of the policy itself, not because of the proposed changes themselves.

2024-01-31 23:35 UTC, bensternthal commented
@tobie good call, I am working to get the IP policy reviewed and updated. Once that is live I will merge this PR.

2024-02-01 22:13 UTC, tobie approved these changes
Both concerned addressed. Thank you!!

2024-02-02 17:40 UTC, UlisesGascon approved these changes

2024-02-06 16:45 UTC, joesepi approved these changes

2024-02-06 18:07 UTC, mcollina approved these changes
lgtm

2024-02-14 10:53 UTC, mcollina approved these changes
lgtm

2024-02-15 22:27 UTC, merged