Update CPC Regular Member Process
openjs-foundation/cross-project-council pull request #1326
Opened 2024-06-28 21:23 UTC by bensternthal

This PR updates the Regular member joining process to use the google form and takes into account feedback regarding the lazy consensus process outlined in #1324

2024-06-28 22:32 UTC, tobie approved these changes

2024-07-02 21:50 UTC, mhdawson approved these changes
LGTM

2024-07-02 21:51 UTC, mhdawson commented
@bensternthal thanks for putting this together, and also pulling in approach recently discussed around travel fund approvals.

2024-07-02 21:53 UTC, ctcpip requested changes
looks good, one small issue

2024-07-02 21:53 UTC, ctcpip commented on governance/GOVERNANCE.md
> +### How To Apply As A Regular Member
```suggestion
### How To Apply to Become a Regular Member
```

2024-07-08 20:26 UTC, VoltrexKeyva commented on governance/GOVERNANCE.md
> +   * Add the member to the github `cpc-regular-members` [team][cpc regular members team]
```suggestion
   * Add the member to the GitHub `cpc-regular-members` [team][cpc regular members team]
```

2024-07-08 20:26 UTC, VoltrexKeyva commented on governance/GOVERNANCE.md
> +* If you are not approved you will be notified privately via email
```suggestion
* If you are not approved you will be notified privately via email.
```

2024-07-09 21:36 UTC, ctcpip commented on governance/GOVERNANCE.md
> +One must already be an Active OpenJS Collaborator, as described below, to be eligible to become a Regular Member of the CPC.
```suggestion
One must already be an [Active OpenJS Collaborator], as described below, to be eligible to become a Regular Member of the CPC.
```

2024-07-09 21:36 UTC, ctcpip commented on governance/GOVERNANCE.md
> +One must already be an Active OpenJS Collaborator, as described below, to be eligible to become a Regular Member of the CPC.
this resolves the lint failure

2024-07-09 21:55 UTC, ctcpip approved these changes

2024-07-09 21:55 UTC, merged