Merge Working Groups and Collaboration Spaces
openjs-foundation/cross-project-council pull request #1339
Opened 2024-07-14 15:44 UTC by tobie

Closes #1110

2024-07-14 15:49 UTC, ljharb approved these changes

2024-07-14 15:49 UTC, ljharb commented on collaboration-spaces/COLLABORATION_NETWORK.md
> +The Cross Project Council (CPC) main delegate scoped authority to a collaboration space. In such cases, the collaboration space may formally represent the Foundation, for example in a standards organ
```suggestion
The Cross Project Council (CPC) may delegate scoped authority to a collaboration space. In such cases, the collaboration space may formally represent the Foundation, for example in a standards organization.
```

2024-07-15 16:41 UTC, UlisesGascon approved these changes

2024-07-15 17:03 UTC, rxmarbles approved these changes

2024-07-15 17:43 UTC, ctcpip commented on collaboration-spaces/COLLABORATION_SPACE_PROGRESSION.md
> +`Collaboration Spaces` are intended to expand the group of contributors to the work of the OpenJS Foundation's work by allowing people outside the OpenJS member projects to propose/collaborate on are
```suggestion
`Collaboration Spaces` aim to expand the group of contributors to the OpenJS Foundation by enabling individuals outside of OpenJS Foundation projects to propose and collaborate on areas important to the JavaScript ecosystem.
```

suggestion for clarity

2024-07-15 17:45 UTC, ctcpip commented on governance/GOVERNANCE.md
> +Pull requests that change governance of the CPC (including changes to [auhtority delegation to Collaboration Spaces](./COLLABORATION_NETWORK.md#authority-delegation)) must meet the following conditio
```suggestion
Pull requests that change governance of the CPC (including changes to [authority delegation to Collaboration Spaces](./COLLABORATION_NETWORK.md#authority-delegation)) must meet the following conditions in addition to the ones listed for regular PRs:
```

2024-07-15 17:47 UTC, ctcpip requested changes
looks good.  couple small issues

2024-07-15 19:35 UTC, ctcpip approved these changes

2024-07-15 21:32 UTC, rxmarbles approved these changes

2024-07-20 15:27 UTC, ovflowd approved these changes

2024-07-25 15:02 UTC, VoltrexKeyva commented on governance/GOVERNANCE.md
> +
Is this second newline intentional?

2024-07-25 15:02 UTC, VoltrexKeyva commented on governance/GOVERNANCE.md
> +Pull requests that change governance of the CPC (including changes to [authority delegation to Collaboration Spaces](./COLLABORATION_NETWORK.md#authority-delegation)) must meet the following conditio
```suggestion
Pull requests that change the governance of the CPC (including changes to [authority delegation to Collaboration Spaces](./COLLABORATION_NETWORK.md#authority-delegation)) must meet the following conditions in addition to the ones listed for regular PRs:
```

2024-07-26 17:48 UTC, tobie commented on collaboration-spaces/COLLABORATION_NETWORK.md
> +* facilitate when different projects' needs conflict resolution
So there was a copy paste error at some point. The [original text](https://github.com/openjs-foundation/standards/issues/58#issuecomment-597256462) reads _"facilitate when different projects' needs conflict"_, so I'll go ahead and change it accordingly.

```suggestion
* facilitate when different projects' needs conflict
```

2024-07-26 17:48 UTC, tobie commented on governance/GOVERNANCE.md
> +
```suggestion
```

2024-07-26 17:50 UTC, tobie commented on governance/GOVERNANCE.md
> +Pull requests that change governance of the CPC (including changes to [authority delegation to Collaboration Spaces](./COLLABORATION_NETWORK.md#authority-delegation)) must meet the following conditio
```suggestion
Pull requests that change CPC governance (including changes to [authority delegation to Collaboration Spaces](./COLLABORATION_NETWORK.md#authority-delegation)) must meet the following conditions in addition to the ones listed for regular PRs:
```

2024-07-26 18:11 UTC, tobie commented
This got board approval today. Now only waiting on #1336.

2024-08-01 22:03 UTC, erickzhao approved these changes

2024-08-20 23:03 UTC, merged

2024-08-21 09:30 UTC, Rockyspade reviewed
collaboration-spaces/COLLABORATION_NETWORK.md $gh update merger status #1330 #205

2024-11-22 15:19 UTC, Playaset reviewed
#1386 #1367 #1088 #1397 #1386