Add policy for deleting CPC repo content
openjs-foundation/cross-project-council pull request #1358
Opened 2024-08-20 18:11 UTC by tobie

Closes #1346.

2024-08-21 21:34 UTC, ctcpip requested changes
minor suggestions for clarity, grammar, spelling

2024-08-21 21:34 UTC, ctcpip commented on governance/GOVERNANCE.md
> +The CPC aims to keep this repository up to date and void of obsolte information. The default is therefore to remove obsolete information. It is always possible to open a pull request to re-include de
```suggestion
The CPC aims to keep this repository up-to-date and devoid of obsolete information. The default is therefore to remove obsolete information. It is always possible to open a pull request to restore deleted information. Please explain the rationale for doing so in that case, and ensure such information is clearly labeled as obsolete.
```

2024-08-21 21:34 UTC, ctcpip commented on governance/GOVERNANCE.md
> +In order to make it easier to search for deleted information in the website, it is recommended to pay particular attention to commit messages when deleting content. In particular, note what content i
```suggestion
To facilitate locating deleted information, please pay close attention to commit messages when deleting content. In particular, note what content is being removed and why.
```

2024-08-21 21:44 UTC, ctcpip approved these changes

2024-08-22 09:43 UTC, mertcanaltin approved these changes
lgtm

2024-08-22 10:16 UTC, sheplu approved these changes
LGTM

2024-08-22 17:39 UTC, UlisesGascon approved these changes

2024-08-23 11:03 UTC, merged