Update to staging process
openjs-foundation/cross-project-council pull request #668
Opened 2020-10-20 16:59 UTC by mhdawson

Update to staging process based on discussion in 
CPC meeting

2020-10-20 16:59 UTC, mhdawson commented
Node: from discussion in the CPC meeting we will also need to
restructure the existing proposal directory

2020-10-20 17:08 UTC, joesepi commented
I guess when you do the work in the Github UI, it doesn't show as a renamed file with updates to that file. Oh well. Regardless, I think we tweaked enough of the language to just look at is as a fresh file as shown in the pull request.

2020-10-20 18:51 UTC, ljharb approved these changes

2020-10-20 18:51 UTC, ljharb commented on PROPOSAL_PROCESS.md
> +An incubating proposal can be updated through ss many PRs as you’d like, essentially providing snapshots
```suggestion
An incubating proposal can be updated through as many PRs as you’d like, essentially providing snapshots
```

2020-10-27 18:20 UTC, joesepi approved these changes
Thanks. We can restructure the files/folders once we have more reviewers.

2020-10-27 23:59 UTC, dmethvin approved these changes

2020-10-30 14:03 UTC, eemeli requested changes
The change request is just for the possibly-misplaced line. Overall I definitely approve of this.

As a bit of a dogfooding exercise, should this change follow its own suggested process?

2020-10-30 14:03 UTC, eemeli commented on PROPOSAL_PROCESS.md
> +stakeholders (including the board) have had a chance to review and request changes, and determine whether further iteration is needed.
```suggestion
stakeholders (potentially including the board) have had a chance to review and request changes, and determine whether further iteration is needed. 
```

2020-11-03 17:22 UTC, eemeli approved these changes

2020-11-03 17:23 UTC, merged