doc: add travel fund allocation for 2021
openjs-foundation/cross-project-council pull request #725
Opened 2021-03-04 18:02 UTC by mhdawson

Add amount approved by board for 2021

2021-03-04 18:14 UTC, mhdawson commented on project-resources/MEMBER_TRAVEL_FUND.md
> +for a 2020 joint travel fund was approved in the amount of $20,000 (lower this year
```
for a 2021 joint travel fund was approved in the amount of $20,000 (lower this year
```

2021-03-04 18:22 UTC, joesepi approved these changes
Thanks for the update.

I will also have some travel fund housekeeping updates that I started today. Simply moving 2020 to archived and adding a new 2021 file and updating links and adding a very simple readme to the travel fun directory pointing to the documentation in the project-resources file.

2021-03-04 18:28 UTC, brianwarner commented
This time around I would also recommend using the [LFX crowdfunding tool](https://crowdfunding.lfx.linuxfoundation.org/#projects) to handle actual reimbursement. It can be set up specifically for travel funds, and can also receive donations from organizations other than the Foundation.

To my knowledge it can't replace the actual decision process (e.g., CPC still needs a way to track and approve applications, and avoid overspending the budget) but it does provided a streamlined process to actually get paid, and provides a transparent ledger.

2021-03-04 18:31 UTC, christian-bromann approved these changes

2021-03-06 13:02 UTC, tobie requested changes
The Member Travel Fund allocation process focusses on helping underserved communities in particular. If there is a year in which underserved communities are suffering [it is this year](https://www.cdc.gov/coronavirus/2019-ncov/community/health-equity/race-ethnicity.html).

In this context, cutting down this fund without reassigning the savings into a program that does the same kind of work sends the wrong signal and isn't aligned with the values we are trying to defend, notably in #699.

While we don't necessarily have a program setup just yet, we should request from the Board a formal commitment to earmark the saved funds for DEI-related work and have it mentioned in this PR.

2021-05-05 18:02 UTC, mhdawson commented
@tobie this was discussed in latest Board finance committee meeting, and the a recommendation was made to the board. Based on that recommendation the board approved changing the total back to $60k, changing the budget line item to `community fund` with the expectation the the CPC will propose additional review/approval processes for spending the money beyond just travel.  

I think next steps after this lands is for CPC to work on proposals for other ways the fund may be used.

2021-05-06 08:18 UTC, tobie approved these changes
This is a great outcome! Thank you for your advocacy and the Board members for their understanding.

2021-05-06 08:34 UTC, tobie commented
> I think next steps after this lands is for CPC to work on proposals for other ways the fund may be used.

Tracking this in #756.

2021-05-06 21:16 UTC, mhdawson commented
I'll leave this until next CPC meeting so we can give an update to the full team before landing.

2021-05-25 17:26 UTC, tobie commented
Update was given to the CPC. Tracking the proposal that the CPC has to make in #756. This can be merged.

2021-05-25 18:04 UTC, merged