Update project infrastructure documentation
openjs-foundation/cross-project-council pull request #879
Opened 2022-04-28 20:09 UTC by brianwarner

This commit removes references to the Directory generator, which has been deprecated. The LF now
has a centrally maintained tool that does this for us.

There are also a few other changes to the project tooling guidance that have occurred over the past
few years, and the documentation had gotten a little stale. This commit includes updates where
appropriate.

Signed-off-by: Brian Warner <brian@bdwarner.com>

2022-04-28 20:16 UTC, joesepi approved these changes
LGTM. Thanks!

2022-04-28 20:19 UTC, joesepi commented
FYI: Even though the changes to our GOVERNANCE in this PR are minimal, I believe this language from our GOVERNANCE still applies:

>Pull requests that change governance of the CPC (including approving changes to Working Groups) must meet the following conditions in addition to the ones listed for regular PRs.
>
>The PR has been open for at least 14 days OR consensus is reached in a meeting with quorum of voting members.

https://github.com/openjs-foundation/cross-project-council/blob/main/governance/GOVERNANCE.md#merging-prs-into-this-repository

2022-04-28 20:37 UTC, ljharb approved these changes

2022-04-29 08:27 UTC, VoltrexMaster approved these changes

2022-04-29 21:12 UTC, achrinza approved these changes

2022-05-02 21:19 UTC, mhdawson approved these changes
LGTM

2022-07-19 14:09 UTC, tobie commented on governance/GOVERNANCE.md
> +* Ask the LF to add the member to the `cpc-private` email list
This needs to be made a little more explicit. Especially "the LF" needs to be at the very least expanded. Ideally an email address or link to a ticketing system should be provided.

2022-07-19 14:18 UTC, tobie requested changes
Lots of welcomed cleanup, here. Thank you!

I do want to gently push back against merging OpenJSF's continuity planning with the LF's. Sure the LF's responsible for operations, but the two organizations are independent, and separating accounts for the two seems like a healthy and cheap best practice.

2022-07-19 14:25 UTC, ljharb commented on project-resources/INFRASTRUCTURE_MENU.md
> +**For all project services, please add an OpenJS or Linux Foundation account at an owner or highest-level of permission access.**  This helps ensure continuity by reducing the bus factor on the proje
the LF isn’t a service provider, it’s the parent organization as i understand it - it’s not likely to ever change.

2022-07-21 10:21 UTC, tobie commented on project-resources/INFRASTRUCTURE_MENU.md
> +**For all project services, please add an OpenJS or Linux Foundation account at an owner or highest-level of permission access.**  This helps ensure continuity by reducing the bus factor on the proje
Centralization is _always_ more operationally efficient. It also creates vendor lock-in (which negatively impacts an org's ability to negotiate agreements, even if intends to stay with the same vendor).

As always, balancing between the two should be done on a case per case basis (it's basically a cost/benefit ratio analysis).

Here, given that projects had to include the OpenJSF's GitHub account up until now, opening that up to now also include the LF's GitHub account isn't going to create any operational efficiency (unless there's a plan to deprecate the OpenJSF account down the line).

2022-09-02 20:39 UTC, bnb commented
+1 to @tobie's request. Given how the Foundations are structured and the general spirit of how we've approached setting up structures for the OpenJS Foundation's independence in the past, I'd wildly prefer the separation.

2022-09-02 20:39 UTC, bnb requested changes
formalizing my previous comment

2022-09-06 14:42 UTC, joesepi commented
@tobie and @bnb I think these changes are documenting how things are currently. If we want to request changes, that probably should happen in its own issue.

2022-09-06 14:45 UTC, bnb commented
@joesepi given this hasn't landed in 4 months, I'd rather we change it and get it fixed in this PR (or a replacement) over merging something two CPC members are -1 on.

2022-09-06 15:10 UTC, joesepi commented
So the request is to delay landing a PR that accurately documents how things exist today, to make changes to how things exist today and then land the PR to reflect those changes? Changes that may take time. And during that time, our documentation should remain out of date?

I think these are two different things. I think our documentation should be accurate (land this PR) and we should open a new issue to address the concerns raised in this issue.

How long this PR has been open is besides the point in my mind. We were just talking about cleaning up the repo, and this is something that had fallen off the radar. But now that it is back on the radar, I think we should merge it and move the concerns to a new issue.

If I am misunderstanding, please correct me.
If we want to hold off on having accurate documentation to make changes to process, I dont think that is a great idea.

2022-09-06 16:08 UTC, joesepi commented
Hey @bnb and @tobie -- @theheels is going to look into how things exist today to confirm and then we can figure out how to move forward on this PR. Thanks, everyone.

2022-10-18 18:10 UTC, bnb commented on project-resources/INFRASTRUCTURE_MENU.md
> +By default all OpenJS Foundation projects have open source repositories in their own GitHub Organizations.  The `thelinuxfoundation` admin account must be added as owner for each organization.  Two-f
FWIW this is not the case for `nodejs` or `electron`, and as Electron's voting member my understanding is that we would 100% not be okay with this at present without direct discussion with the Foundation's staff on details.

2022-10-18 18:12 UTC, bnb commented on project-resources/INFRASTRUCTURE_MENU.md
> +* The [Amethyst theme](https://github.com/qunitjs/jekyll-theme-amethyst) is maintained by @krinkle for use with GitHub Pages.
Extremely -1 on us calling out free things in this document. It devalues the non-free things that the Foundation *does* provide.

2022-10-18 18:21 UTC, bnb commented on project-resources/INFRASTRUCTURE_MENU.md
> +
AFAIK this is free for anyone, and should not be included here.

2022-10-18 18:30 UTC, bnb commented on project-resources/INFRASTRUCTURE_MENU.md
>  ## Open Source Dependency Monitoring (FOSSA)
We should probably drop this? Unclear, it's just a heading.

2022-10-18 18:30 UTC, bnb commented on project-resources/INFRASTRUCTURE_MENU.md
> +The OpenJS Foundation can provide credential storage and sharing. Because the credentials are shared through a LastPass Enterprise account, each user only needs a free account to receive them.  Manag
Do we still use LastPass Enterprise?

2022-10-18 18:31 UTC, bnb commented on project-resources/INFRASTRUCTURE_MENU.md
> +Projects are welcome to create channels on the [OpenJS Foundation Slack](https://openjs-foundation.slack.com), or set up their own free Slack workspace.
```suggestion
Projects are welcome to create channels on the [OpenJS Foundation Slack](https://openjs-foundation.slack.com).
```

2022-10-18 18:32 UTC, bnb commented on project-resources/INFRASTRUCTURE_MENU.md
> +Projects may request that standing meetings be added to the [OpenJS Foundation calendar](https://calendar.openjsf.org).  The OpenJS Foundation currently has multiple Zoom accounts capable of livestre
This feels like it should probably be two separate points - calendar being one, streaming being another.

2025-04-15 21:34 UTC, tosh7431 approved these changes

2025-04-15 23:02 UTC, bensternthal commented
This PR seems very out of date, and the two documents it references have had major updates since this was filed. I recommend this be closed.

2025-04-20 08:08 UTC, closed without merging