Define approving process for changes to the Code of Conduct
openjs-foundation/cross-project-council pull request #889
Opened 2022-05-18 12:31 UTC by christian-bromann

In the [last CPC working group session](https://hackmd.io/XmcHdDDARLm_lSXMIj_J7Q) we have been working on some CoC issues and realised that we don't have a clear definition on the approval process for them. To have more clarity here we suggest to align the condition for merging changes to the CoC with changes to the governance of the CPC.

cc @jorydotcom @joesepi @SaraJo

2022-05-18 13:22 UTC, joesepi approved these changes
LGTM. Thanks!

2022-05-18 14:47 UTC, rginn commented
+1 Thanks!

2022-05-18 14:55 UTC, ljharb approved these changes

2022-05-18 16:24 UTC, jorydotcom approved these changes

2022-05-19 20:47 UTC, mhdawson approved these changes
LGTM

2022-05-20 11:00 UTC, eemeli requested changes
If we're expanding the scope of what's covered by the "governance of the CPC", we should make it really clear what is in fact covered. I would like this PR to include an explicit list of links to documents that is considered within the scope of that phrase. This should also make later changes easier to apply.

On the general idea of including the CoC to be a part of the "governance of the CPC", I definitely agree.

2022-05-24 18:21 UTC, tobie approved these changes

2022-07-28 14:18 UTC, designMoreWeb approved these changes
+1 great looks good to me

2022-08-04 18:45 UTC, WaleedAshraf approved these changes

2022-08-30 16:48 UTC, eemeli commented on governance/GOVERNANCE.md
> +[governance of the CPC]: ./
@christian-bromann Have you had a chance to look at this?

2022-10-18 18:18 UTC, mikesamuel commented
The remaining issue seems to be defining an appropriate link for

    [governance of the CPC]: ./

used in this context

> Pull requests that do not change the charter or **governance of the CPC** can be merged into
this repository provided the following conditions have been met:

as [pointed out](https://github.com/openjs-foundation/cross-project-council/pull/889#discussion_r878019912) by @eemeli.

Since the affected file is `governance/GOVERNANCE.md` it seems like the context is apparent without a link.
Could we do away with the link and get the rest committed?

2022-12-12 00:18 UTC, ovflowd commented
Just a friendly bump to see if the requested changes can be addressed?

2023-02-08 11:57 UTC, eemeli commented on governance/GOVERNANCE.md
> +[governance of the CPC]: ./
@christian-bromann Ping?

2024-02-24 21:37 UTC, tobie commented
Obsoleted by https://github.com/openjs-foundation/cross-project-council/pull/1135 (the CPC is responsible for CoC changes).

2024-02-24 21:37 UTC, closed without merging