chore: update Electron reps
openjs-foundation/cross-project-council pull request #922
Opened 2022-08-02 16:07 UTC by bnb

updates one Electron rep to @erickzhao, removing @codebytere (thank you @codebytere <3), and updating my personal employment.

2022-08-02 16:16 UTC, dylans approved these changes

2022-08-02 16:18 UTC, erickzhao requested changes

2022-08-02 16:18 UTC, erickzhao commented on README.md
> +- **Electron**: Erick Shao ([@erickzhao](https://github.com/erickzhao), Slack) & Tierney Cyren ([@bnb](https://github.com/bnb), Twilio)
```suggestion
- **Electron**: Erick Zhao ([@erickzhao](https://github.com/erickzhao), Slack) & Tierney Cyren ([@bnb](https://github.com/bnb), Twilio)
```

typo 😅

2022-08-02 16:39 UTC, bnb commented on README.md
> +- **Electron**: Erick Shao ([@erickzhao](https://github.com/erickzhao), Slack) & Tierney Cyren ([@bnb](https://github.com/bnb), Twilio)
Ah my sincere apologies.

2022-08-02 16:42 UTC, erickzhao approved these changes

2022-08-03 18:28 UTC, ljharb approved these changes

2022-08-04 01:36 UTC, VoltrexMaster approved these changes

2022-08-04 08:02 UTC, eemeli approved these changes

2022-08-04 10:05 UTC, tobie approved these changes

2022-08-05 17:11 UTC, mhdawson approved these changes
LGTM

2022-08-30 16:45 UTC, joesepi approved these changes

2022-09-01 07:07 UTC, WaleedAshraf approved these changes

2022-09-01 09:21 UTC, mcollina approved these changes
lgtm

2022-09-07 15:58 UTC, mhdawson commented
I assume this can land as it's been open for a long time and has lots of approvals.

2022-09-07 15:58 UTC, merged