chore(expenses): claudio wunder - collab summit
openjs-foundation/cross-project-council pull request #933
Opened 2022-09-10 14:33 UTC by ovflowd

**Request for:** Collab Summit
**Dates:** 30th September - 3rd October
**Travelling from:** Munich
**Flight:** ~380 USD
**Hotel:** ~670 USD
**Total:** ~1050 USD

The member will pay all other costs like Transportation and Food. No expensing is needed.

Signed-off-by: Claudio Wunder <cwunder@gnome.org>

2022-09-10 14:34 UTC, bnb approved these changes

2022-09-10 15:36 UTC, Trott approved these changes

2022-09-11 09:27 UTC, WaleedAshraf requested changes

2022-09-11 09:27 UTC, WaleedAshraf commented on TRAVEL_FUND/2022.md
> +Claudio | Wunder | Collab Summit | Project Member || Ireland | 30 Sept - 3 Oct 2022 | 1825 USD | 10 Sept 2022 | tbd
```suggestion
Claudio | Wunder | Collab Summit | Project Member || Ireland | 30 Sept - 3 Oct 2022 | 1050 USD | 10 Sept 2022 | tbd
||||||| Total | 21,909.59 USD |
```

2022-09-11 11:47 UTC, mcollina approved these changes
lgtm

2022-09-11 13:19 UTC, ovflowd commented on TRAVEL_FUND/2022.md
> +Claudio | Wunder | Collab Summit | Project Member || Ireland | 30 Sept - 3 Oct 2022 | 1825 USD | 10 Sept 2022 | tbd
Tru! Forgot to update the text there 🙈

2022-09-11 13:19 UTC, ovflowd commented
@WaleedAshraf I updated the doc 🙌

2022-09-11 14:18 UTC, WaleedAshraf approved these changes

2022-09-11 14:27 UTC, tobie approved these changes

2022-09-12 17:30 UTC, dylans approved these changes

2022-09-12 17:45 UTC, mhdawson approved these changes
LGTM

2022-09-12 18:12 UTC, ovflowd commented
Hey folks 👋 from the day I created this issue to today, the flight price increased to 430 USD. Would this price still be OK? (I'm going to book the flight now regardless, so if the new price is not okay, I just expense the original price).

2022-09-12 18:13 UTC, ovflowd commented
cc @tobie @mcollina @dylans @bnb @Trott @WaleedAshraf @mhdawson (need a re-approval)

2022-09-12 18:28 UTC, ljharb approved these changes

2022-09-12 22:51 UTC, WaleedAshraf commented
@ovflowd you can merge this as it has got enough approvals.
When you are going to expense it after the event, you can create a new PR to update the amount with the actual price.

2022-09-12 22:59 UTC, bnb commented
> 
Hey folks 👋 from the day I created this issue to today, the flight price increased to 430 USD. Would this price still be OK? (I'm going to book the flight now regardless, so if the new price is not okay, I just expense the original price).

IMO yes, that's fine.

2022-09-12 23:00 UTC, merged