doc: add bullet to onboarding checklist in PROJECT_PROGRESSION.md
openjs-foundation/cross-project-council pull request #981
Opened 2022-12-06 19:48 UTC by bnb

adds an additional checklist item that allows us to cross off the actual transfer of IP while onboarding.

2022-12-06 19:50 UTC, anonrig approved these changes

2022-12-06 20:14 UTC, ljharb approved these changes

2022-12-09 21:46 UTC, tobie requested changes
So it seems we already have language related to this on line 117, with the IP transfer actually happening _after_ graduation and tracked in the [post-graduation checklist](https://github.com/openjs-foundation/cross-project-council/blob/9a9de580973d131d0c852c6fb363934644f35e0c/PROJECT_PROGRESSION.md#post-graduation-checklist).

I'd leave this as is, unless this is isn't how the process is actually handled.

2022-12-10 20:14 UTC, ovflowd commented on PROJECT_PROGRESSION.md
>  - [ ] List trademarks the project commits to transfer to the OpenJS Foundation following graduation
Maybe this line could then be rephrased to make it more implicit that any pending trademark should be transferred from the original project?

2023-06-30 14:08 UTC, closed without merging

2023-06-30 14:09 UTC, tobie commented
Closing, per https://github.com/openjs-foundation/cross-project-council/pull/981#pullrequestreview-1212288557.